name: Smoke Tests

# Controls when the workflow will run
on: [push, pull_request, workflow_dispatch]

env:
  MAX_ATTEMPTS: 3
  TIMEOUT: 10

jobs:
  pro:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        cluster: [v1.20.2, v1.19.7, v1.18.15, v1.17.17, v1.16.15]
        mode: [tyk-pro,tyk-cp]
    steps:
      - uses: actions/checkout@v2

      - name: Create Kind Cluster
        uses: engineerd/setup-kind@v0.5.0
        with:
          version: "v0.11.1"
          config: .github/kind-cluster-${{ matrix.cluster }}.yml

      - name: Install helm
        uses: Azure/setup-helm@v1.1
        with:
          version: v3.5.3

      - name: Deploy basic ${{ matrix.mode }}
        uses: nick-invision/retry@v2
        with:
          max_attempts: ${{ env.MAX_ATTEMPTS }}
          timeout_minutes: ${{ env.TIMEOUT }}
          command: |
            LICENSE="${{ secrets.DASH_LICENSE }}" \
            MDCB_LICENSE="${{ secrets.MDCB_LICENSE }}" \
            ./up.sh \
              --namespace ${{ matrix.mode }} \
              ${{ matrix.mode }}

      - name: Deploy ${{ matrix.mode }} with a redis cluster
        uses: nick-invision/retry@v2
        with:
          max_attempts: ${{ env.MAX_ATTEMPTS }}
          timeout_minutes: ${{ env.TIMEOUT }}
          command: |
            LICENSE="${{ secrets.DASH_LICENSE }}" \
            MDCB_LICENSE="${{ secrets.MDCB_LICENSE }}" \
            ./up.sh \
              --namespace ${{ matrix.mode }}-redis-cluster \
              --redis redis-cluster \
              ${{ matrix.mode }}

      # - name: Deploy ${{ matrix.mode }} with postgres
      #   uses: nick-invision/retry@v2
      #   with:
      #     max_attempts: ${{ env.MAX_ATTEMPTS }}
      #     timeout_minutes: ${{ env.TIMEOUT }}
      #     command: |
      #       LICENSE="${{ secrets.DASH_LICENSE }}" \
      #       MDCB_LICENSE="${{ secrets.MDCB_LICENSE }}" \
      #       ./up.sh \
      #         --namespace ${{ matrix.mode }}-postgres \
      #         --database postgres \
      #         ${{ matrix.mode }}

  hybrid:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        cluster: [v1.20.2, v1.19.7, v1.18.15, v1.17.17, v1.16.15]
    steps:
      - uses: actions/checkout@v2

      - name: Create Kind Cluster
        uses: engineerd/setup-kind@v0.5.0
        with:
          version: "v0.11.1"
          config: .github/kind-cluster-${{ matrix.cluster }}.yml

      - name: Install helm
        uses: Azure/setup-helm@v1.1
        with:
          version: v3.5.3

      - name: Deploy basic tyk-hybrid
        uses: nick-invision/retry@v2
        with:
          max_attempts: ${{ env.MAX_ATTEMPTS }}
          timeout_minutes: ${{ env.TIMEOUT }}
          command: |
            TYK_HYBRID_CONNECTIONSTRING="${{ secrets.HYBRID_MDCB_HOST }}" \
            TYK_HYBRID_ORGID="${{ secrets.HYBRID_RPC_KEY }}" \
            TYK_HYBRID_AUTHTOKEN="${{ secrets.HYBRID_API_KEY }}" \
            ./up.sh \
              --namespace tyk-hybrid \
              tyk-hybrid

      - name: Deploy tyk-hybrid with a redis cluster
        uses: nick-invision/retry@v2
        with:
          max_attempts: ${{ env.MAX_ATTEMPTS }}
          timeout_minutes: ${{ env.TIMEOUT }}
          command: |
            TYK_HYBRID_CONNECTIONSTRING="${{ secrets.HYBRID_MDCB_HOST }}" \
            TYK_HYBRID_ORGID="${{ secrets.HYBRID_RPC_KEY }}" \
            TYK_HYBRID_AUTHTOKEN="${{ secrets.HYBRID_API_KEY }}" \
            ./up.sh \
              --namespace tyk-hybrid-redis-cluster \
              --redis redis-cluster \
              tyk-hybrid

  oss:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        cluster: [v1.20.2, v1.19.7, v1.18.15, v1.17.17, v1.16.15]
    steps:
      - uses: actions/checkout@v2

      - name: Create Kind Cluster
        uses: engineerd/setup-kind@v0.5.0
        with:
          version: "v0.11.1"
          config: .github/kind-cluster-${{ matrix.cluster }}.yml

      - name: Install helm
        uses: Azure/setup-helm@v1.1
        with:
          version: v3.5.3

      - name: Deploy basic tyk-gateway
        uses: nick-invision/retry@v2
        with:
          max_attempts: ${{ env.MAX_ATTEMPTS }}
          timeout_minutes: ${{ env.TIMEOUT }}
          command: |
            ./up.sh \
              --namespace tyk-gateway \
              tyk-gateway

      - name: Deploy tyk-gateway with a redis cluster
        uses: nick-invision/retry@v2
        with:
          max_attempts: ${{ env.MAX_ATTEMPTS }}
          timeout_minutes: ${{ env.TIMEOUT }}
          command: |
            ./up.sh \
              --namespace tyk-gateway-redis-cluster \
              --redis redis-cluster \
              tyk-gateway
